services:
  - type: web
    name: tennis-fragolino-bot
    env: python
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y tesseract-ocr tesseract-ocr-eng tesseract-ocr-ita
      pip install -r requirements.txt
    startCommand: python bot.py
